In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [3]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [3]:
import torch
a = torch.ones(3)

In [5]:
a

tensor([1., 1., 1.])

In [6]:
a[1]


tensor(1.)

In [7]:
float(a[1])

1.0

In [9]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [10]:
points = torch.zeros(6)

In [11]:
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

points

tensor([4., 1., 5., 3., 2., 1.])

In [13]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [15]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [17]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [18]:
points.shape

torch.Size([3, 2])

In [19]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [20]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [21]:
points[0, 1]

tensor(1.)

In [25]:
img_t = torch.randn(3,5,5)
weights = torch.tensor([0.2126, 0.7152, 0.0722])

batch_t = torch.randn(2, 3, 5, 5)

img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [3]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1,2], [3, 4]], dtype=torch.short)

In [4]:
short_points.dtype

torch.int16

In [5]:
double_points = torch.ones(10, 2).double()

In [6]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [4]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')
points = 2 * points_gpu

In [9]:
torch.save(points_gpu, 'data.t')


In [8]:
import h5py

f = h5py.File('data3.hdf5', 'w')
dset = f.create_dataset('coords', data=points_gpu.cpu().numpy())
f.close()

In [9]:
test_list = list(range(9))

In [10]:
test_points = torch.Tensor(test_list)

In [15]:
test_points.storage()
test_points.stride()

(1,)

In [17]:
b = test_points.view(3, 3)